
export default {
  PHONE_NUMBER: {
    BEFORE: 'PHONE_NUMBER--BEFORE',
    SUCCESS: 'PHONE_NUMBER--SUCCESS',
    FAILURE: 'PHONE_NUMBER--FAILURE'
  },
  VALIDATE_DEVICE: {
    BEFORE: 'VALIDATE_DEVICE--BEFORE',
    SUCCESS: 'VALIDATE_DEVICE--SUCCESS',
    FAILURE: 'VALIDATE_DEVICE--FAILURE'
  },
  GET_USER: {
    BEFORE: 'GET_USER--BEFORE',
    SUCCESS: 'GET_USER--SUCCESS',
    FAILURE: 'GET_USER--FAILURE'
  },
  POST_USER: {
    BEFORE: 'POST_USER--BEFORE',
    SUCCESS: 'POST_USER--SUCCESS',
    FAILURE: 'POST_USER--FAILURE'
  },
  LOGOUT: {
    BEFORE: 'LOGOUT--BEFORE',
    SUCCESS: 'LOGOUT--SUCCESS',
    FAILURE: 'LOGOUT--FAILURE'
  }
}
