
export default {
  AD: {
    SET_THUMBNAIL: 'AD__SET_THUMBNAIL',
    SET_RATING: 'AD__SET_RATING'
  },

  ACCOUNT: {
    LOGIN: {
      BEFORE: 'ACCOUNT__LOGIN--BEFORE',
      SUCCESS: 'ACCOUNT__LOGIN--SUCCESS',
      FAILURE: 'ACCOUNT__LOGIN--FAILURE'
    },
    LOGOUT: {
      BEFORE: 'ACCOUNT__LOGOUT--BEFORE',
      SUCCESS: 'ACCOUNT__LOGOUT--SUCCESS',
      FAILURE: 'ACCOUNT__LOGOUT--FAILURE'
    }
  },

  ROUTER: {
    PUSH: 'ROUTER__PUSH'
  }
}
